import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import Activity from './Activity2_ConsonantMapDrop.jsx'

vi.mock('./level_1/Level1ConsonantPlacement.jsx', () => ({ default: ({ onComplete }) => <><button onClick={() => onComplete(17, 25, 90, false)}>Finish 17</button><button onClick={() => onComplete(18, 25, 100, false)}>Finish 18</button></> }))
vi.mock('./level_2/Level2CompleteChart.jsx', () => ({ default: ({ onComplete }) => <><button onClick={() => onComplete(28, 40, 110, false)}>Finish 28</button><button onClick={() => onComplete(29, 40, 120, false)}>Finish 29</button></> }))
vi.mock('./level_3/Level3WordMatch.jsx', () => ({ default: ({ onComplete }) => <button onClick={() => onComplete(24, 24, 130, true)}>Finish words</button> }))
beforeEach(() => {
  const saved = new Map()
  vi.stubGlobal('localStorage', { getItem: (key) => saved.get(key) ?? null, setItem: (key, value) => saved.set(key, value) })
})
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
it('requires 70 percent or above at each stage, summarizes results, and persists unlocks', () => {
  render(<Activity />)
  const next = screen.getByRole('button', { name: 'Level 2: Complete the Chart' })
  const last = screen.getByRole('button', { name: 'Level 3: Match Words' })
  expect(next).toBeDisabled()
  expect(last).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: 'Finish 17' }))
  expect(next).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: 'Finish 18' }))
  expect(next).toBeEnabled()
  expect(last).toBeDisabled()
  fireEvent.click(next)
  fireEvent.click(screen.getByRole('button', { name: 'Finish 28' }))
  expect(last).toBeEnabled()
  fireEvent.click(screen.getByRole('button', { name: 'Finish 29' }))
  expect(last).toBeEnabled()
  fireEvent.click(last)
  fireEvent.click(screen.getByRole('button', { name: 'Finish words' }))
  fireEvent.click(screen.getByRole('button', { name: 'Overall summary' }))
  expect(screen.getByRole('heading', { name: 'Consonant Map Drop: Overall Summary' })).toBeInTheDocument()
  expect(screen.getByText('Overall grade: 71/89 (80%)')).toBeInTheDocument()
  expect(screen.getByText('Total time: 5:50')).toBeInTheDocument()
  expect(within(screen.getByRole('row', { name: /Level 2: Complete the Chart/ })).getByText('29/40')).toBeInTheDocument()
  cleanup()
  render(<Activity />)
  expect(screen.getByRole('button', { name: 'Level 3: Match Words' })).toBeEnabled()
  fireEvent.click(screen.getByRole('button', { name: 'Overall summary' }))
  expect(screen.getByText('Total time: 5:50')).toBeInTheDocument()
})
it('does not skip the first level when stored progress is incomplete', () => {
  window.localStorage.setItem('consonant-map-drop-passing-results', JSON.stringify({ 1: { score: 40, total: 40 } }))
  render(<Activity />)
  expect(screen.getByRole('button', { name: 'Level 2: Complete the Chart' })).toBeDisabled()
  expect(screen.getByRole('button', { name: 'Level 3: Match Words' })).toBeDisabled()
  fireEvent.click(screen.getByRole('button', { name: 'Overall summary' }))
  expect(screen.getByText('Complete all three levels to see your overall grade.')).toBeInTheDocument()
})
