export const oddSoundOutQuestions = [
  { prompt: 'Which consonant is the odd one out?', choices: ['p', 't', 'k', 'v'], answer: 'v', explanation: '/p t k/ are voiceless plosives. /v/ is a voiced fricative.' },
  { prompt: 'Which consonant is the odd one out?', choices: ['b', 'd', 'ɡ', 't'], answer: 't', explanation: '/b d ɡ/ are voiced plosives. /t/ is voiceless.' },
  { prompt: 'Which consonant is the odd one out?', choices: ['f', 'θ', 's', 'z'], answer: 'z', explanation: '/f θ s/ are voiceless fricatives. /z/ is voiced.' },
  { prompt: 'Which consonant is the odd one out?', choices: ['v', 'ð', 'z', 'ʃ'], answer: 'ʃ', explanation: '/v ð z/ are voiced fricatives. /ʃ/ is voiceless.' },
  { prompt: 'Which consonant has a different place of articulation from the others?', choices: ['p', 'b', 'm', 't'], answer: 't', explanation: '/p b m/ are bilabial. /t/ is alveolar.' },
  { prompt: 'Which consonant has a different place of articulation from the others?', choices: ['t', 'd', 's', 'f'], answer: 'f', explanation: '/t d s/ are alveolar. /f/ is labiodental.' },
  { prompt: 'Which consonant has a different manner of articulation from the others?', choices: ['f', 'v', 's', 't'], answer: 't', explanation: '/f v s/ are fricatives. /t/ is a plosive.' },
  { prompt: 'Which consonant has a different manner of articulation from the others?', choices: ['p', 'b', 'k', 's'], answer: 's', explanation: '/p b k/ are plosives. /s/ is a fricative.' },
  { prompt: 'Which vowel is the odd one out?', choices: ['i', 'ɪ', 'ɛ', 'u'], answer: 'u', explanation: '/i ɪ ɛ/ are front vowels. /u/ is a back vowel.' },
  { prompt: 'Which vowel is the odd one out?', choices: ['u', 'ʊ', 'ɑ', 'i'], answer: 'i', explanation: '/u ʊ ɑ/ are back vowels. /i/ is a front vowel.' },
  { prompt: 'Which vowel is the odd one out?', choices: ['u', 'ʊ', 'ɔ', 'i'], answer: 'i', explanation: '/u ʊ ɔ/ are rounded. /i/ is unrounded.' },
  { prompt: 'Which vowel has a different height from the others?', choices: ['i', 'u', 'ɑ', 'ɪ'], answer: 'ɑ', explanation: 'The other vowels are produced high or near-high in the vowel space; /ɑ/ is low.' },
  { prompt: 'Which vowel has a different height from the others?', choices: ['æ', 'ɑ', 'ɛ', 'ɒ'], answer: 'ɛ', explanation: '/æ ɑ ɒ/ are low vowels; /ɛ/ is mid.' },
  { prompt: 'Which vowel is the odd one out?', choices: ['i', 'ɪ', 'æ', 'ɑ'], answer: 'ɑ', explanation: '/i ɪ æ/ are front vowels. /ɑ/ is back.' },
  { prompt: 'Which vowel is the odd one out?', choices: ['i', 'ɪ', 'ɛ', 'u'], answer: 'u', explanation: '/i ɪ ɛ/ are unrounded. /u/ is rounded.' },
].map((question, index) => ({ ...question, id: `odd-sound-out-${index + 1}`, category: index < 8 ? 'Consonants' : 'Vowels' }))
