export const findTheSoundQuestions = [
  ['i', ['see', 'cat', 'book', 'hot'], 'see'],
  ['ɪ', ['feet', 'fish', 'face', 'food'], 'fish'],
  ['ɛ', ['moon', 'fed', 'bike', 'boot'], 'fed'],
  ['æ', ['sit', 'coat', 'map', 'food'], 'map'],
  ['ɑ', ['feet', 'book', 'hot', 'face'], 'hot'],
  ['ʌ', ['bed', 'luck', 'see', 'bike'], 'luck'],
  ['ʊ', ['moon', 'look', 'map', 'bed'], 'look'],
  ['u', ['fish', 'hot', 'moon', 'map'], 'moon'],
  ['ej', ['bed', 'pray', 'bike', 'book'], 'pray'],
  ['aj', ['cat', 'coat', 'five', 'food'], 'five'],
  ['ow', ['fish', 'goat', 'bed', 'cup'], 'goat'],
  ['aw', ['bike', 'see', 'cloud', 'book'], 'cloud'],
  ['ɔj', ['coat', 'cat', 'toy', 'bed'], 'toy'],
  ['ɔ', ['feet', 'short', 'map', 'book'], 'short'],
  ['ə', ['cat', 'see', 'about', 'book'], 'about'],
].map(([symbol, choices, answer], index) => ({ id: `find-the-sound-${index + 1}`, symbol, choices, answer }))
